### ISSUE TITLE
Demo missing script reference.

### ISSUE THREAD

**Issue by 2Hadolphin** [L1247/RPG-Module#1]
Scripts inside stat example scene can not been found after import sample from package.

**Comment by L1247** [comment]
I'm currently tring to make new example scene for stat
Will update new example tomorrow 
or you colud download this project by git and check out previous commits .

**Comment by L1247** [comment]
update beginner scene and code of stat
will update intermediate scene later

**Comment by 2Hadolphin** [comment]
阿星辛苦了!
範例的Script檔案一起導入Asset底下會比較方便查看呦
不然package裡面給VS顯示的都是純文字檔

**Comment by L1247** [comment]
@2Hadolphin 更新囉 連同Skill一起
晚點會再弄一個新的範例是進階的方式
[是這影片的內容](https://youtu.be/rT01i9NOinw)
